create table docs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  doc text check (char_length(doc) > 3),
  public boolean default false,
  created timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table docs enable row level security;

create policy "Individuals can create documents." on docs for
    insert with check (auth.uid() = user_id);
create policy "Individuals can view their own documents. " on docs for
    select using (auth.uid() = user_id);
create policy "Individuals can update their own documents." on docs for
    update using (auth.uid() = user_id);
create policy "Individuals can delete their own documents." on docs for
    delete using (auth.uid() = user_id);