/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  serverBuildTarget: "vercel",
  server: process.env.NODE_ENV === "development" ? undefined : "./server.js",
  appDirectory: "src",
  ignoredRouteFiles: ["**/.*"],
  serverDependenciesToBundle: [
    "@uiball/loaders",
    "nanoid",
    /^rehype.*/,
    /^refractor.*/,
    /^parse-entities.*/,
    /^is-decimal.*/,
    /^is-hexadecimal.*/,
    /^is-alphanumerical.*/,
    /^is-alphabetical.*/,
    /^remark.*/,
    /^unified.*/,
    /^unist.*/,
    /^hast.*/,
    /^bail.*/,
    /^trough.*/,
    /^mdast.*/,
    /^micromark.*/,
    /^decode.*/,
    /^character.*/,
    /^property.*/,
    /^space.*/,
    /^comma.*/,
    /^react-markdown$/,
    /^vfile.*/,
    /^ccount*/,
    /^trim-lines*/,
    /^markdown-table*/,
    "superkey",
  ],
};
